export const skillIcons = [
  "/images/icons/Overall-icon.webp", //Overall
  "/images/icons/Attack-icon.webp", //Attack
  "/images/icons/Defence-icon.webp", //Defence
  "/images/icons/Strength-icon.webp", //Strength
  "/images/icons/Constitution-icon.webp", //Constitution
  "/images/icons/Ranged-icon.webp", //Ranged
  "/images/icons/Prayer-icon.webp", //Prayer
  "/images/icons/Magic-icon.webp", //Magic
  "/images/icons/Cooking-icon.webp", //Cooking
  "/images/icons/Woodcutting-icon.webp", //Woodcutting
  "/images/icons/Fletching-icon.webp", //Fletching
  "/images/icons/Fishing-icon.webp", //Fishing
  "/images/icons/Firemaking-icon.webp", //Firemaking
  "/images/icons/Crafting-icon.webp", //Crafting
  "/images/icons/Smithing-icon.webp", //Smithing
  "/images/icons/Mining-icon.webp", //Mining
  "/images/icons/Herblore-icon.webp", //Herblore
  "/images/icons/Agility-icon.webp", //Agility
  "/images/icons/Thieving-icon.webp", //Thieving
  "/images/icons/Slayer-icon.webp", //Slayer
  "/images/icons/Farming-icon.webp", //Farming
  "/images/icons/Runecrafting-icon.webp", //Runecrafting
  "/images/icons/Hunter-icon.webp", //Hunter
  "/images/icons/Construction-icon.webp", //Construction
  "/images/icons/Summoning-icon.webp", //Summoning
  "/images/icons/Dungeoneering-icon.webp", //Dungeoneering
  "/images/icons/Divination-icon.webp", //Divination
  "/images/icons/Invention-icon.webp", //Invention
  "/images/icons/Archaeology-icon.webp", //Archaeology
];
